on: push
name: build and deploy pages
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - name: Save executable
        uses: actions/upload-artifact@v3
        with:
          name: mn-parks
          path: |
            target/release/mn-park-scraper
            public/
#      - uses: actions-rs/cargo@v1
#        with:
#          command: build
#          args: --release --all-features


#       - run: git checkout HEAD^
#       - run: cargo run > public/index.html









  render:
    name: Render

    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: mn-parks
          check_artifacts: true
          search_artifacts: true
      - run: chmod +x target/release/mn-park-scraper
      - run: target/release/mn-park-scraper > public/index.html
      - run: tar czf artifact.tar public/
 
#       - name: Upload artifact
#         uses: actions/upload-artifact@main
#         with:
#           name: github-pages
#           path: ${{ runner.temp }}/artifact.tar

      - run: ls -lha

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        # if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public 