on: push
name: build the artifact
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release
      - name: Save executable
        uses: actions/upload-artifact@v3
        with:
          name: mn-parks
          path: |
            target/release/mn-park-scraper
            public/
